root = "./backend"
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "backend/bin/main"
cmd = "cd backend/ && go build -o bin/main cmd/server/main.go"
delay = 1000
exclude_dir = ["tmp", "bin"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false